import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import { ReduxProvider } from '@/redux/provider'
import Footer from '@/components/Footer'
import "../styles/style.scss"
// import connectMongoDB from '@/libs/mongodb' 


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // connectMongoDB()
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ReduxProvider> */}
        <Navbar />
        {children}
        {/* </ReduxProvider> */}
        <Footer />
        </body>
    </html>
  )
}
